version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - spotify.client-id=${SPOTIFY_CLIENT_ID}
      - spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
      - spotify.redirect-uri=http://127.0.0.1:8080/callback

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
